itemList = [
  {
    "id": 1,
    "name": "구운 넥꼬리",
    "type": "Red",
    "health": 25,
    "stamina": 8,
    "eitr": 0,
    "duration": 20,
    "healing": 2,
    "weight": 5,
    "stack_size": 20,
    "biome": "목초지",
    "station": "Cooking station",
    "eng_name": "Grilled neck tail",
    "img": "img/foods/1.png"
  },
  {
    "id": 2,
    "name": "요리한 멧돼지고기",
    "type": "Red",
    "health": 30,
    "stamina": 10,
    "eitr": 0,
    "duration": 20,
    "healing": 2,
    "weight": 10,
    "stack_size": 20,
    "biome": "목초지",
    "station": "Cooking station",
    "eng_name": "Cooked boar meat",
    "img": "img/foods/2.png"
  },
  {
    "id": 3,
    "name": "요리한 사슴고기",
    "type": "Red",
    "health": 35,
    "stamina": 12,
    "eitr": 0,
    "duration": 20,
    "healing": 2,
    "weight": 10,
    "stack_size": 20,
    "biome": "목초지",
    "station": "Cooking station",
    "eng_name": "Cooked deer meat",
    "img": "img/foods/3.png"
  },
  {
    "id": 4,
    "name": "멧돼지육포",
    "type": "White",
    "health": 23,
    "stamina": 23,
    "eitr": 0,
    "duration": 30,
    "healing": 2,
    "weight": 5,
    "stack_size": 20,
    "biome": "검은숲",
    "station": "가마솥 [1]",
    "eng_name": "Boar jerky",
    "img": "img/foods/4.png"
  },
  {
    "id": 5,
    "name": "다진고기소스",
    "type": "Red",
    "health": 40,
    "stamina": 13,
    "eitr": 0,
    "duration": 25,
    "healing": 3,
    "weight": 10,
    "stack_size": 10,
    "biome": "검은숲",
    "station": "가마솥 [1]",
    "eng_name": "Minced meat sauce",
    "img": "img/foods/5.png"
  },
  {
    "id": 6,
    "name": "여왕의잼",
    "type": "Yellow",
    "health": 14,
    "stamina": 40,
    "eitr": 0,
    "duration": 20,
    "healing": 2,
    "weight": 10,
    "stack_size": 10,
    "biome": "검은숲",
    "station": "가마솥 [1]",
    "eng_name": "Queen's jam",
    "img": "img/foods/6.png"
  },
  {
    "id": 7,
    "name": "당근스프",
    "type": "Yellow",
    "health": 15,
    "stamina": 45,
    "eitr": 0,
    "duration": 25,
    "healing": 2,
    "weight": 10,
    "stack_size": 10,
    "biome": "검은숲",
    "station": "가마솥 [1]",
    "eng_name": "Carrot soup",
    "img": "img/foods/7.png"
  },
  {
    "id": 8,
    "name": "사슴스튜",
    "type": "Red",
    "health": 45,
    "stamina": 15,
    "eitr": 0,
    "duration": 25,
    "healing": 3,
    "weight": 10,
    "stack_size": 10,
    "biome": "검은숲",
    "station": "가마솥 [1]",
    "eng_name": "Deer stew",
    "img": "img/foods/8.png"
  },
  {
    "id": 9,
    "name": "요리한 생선",
    "type": "Red",
    "health": 45,
    "stamina": 15,
    "eitr": 0,
    "duration": 20,
    "healing": 2,
    "weight": 5,
    "stack_size": 20,
    "biome": "늪지대",
    "station": "Cooking station",
    "eng_name": "Cooked fish",
    "img": "img/foods/9.png"
  },
  {
    "id": 10,
    "name": "먹셰이크",
    "type": "Yellow",
    "health": 16,
    "stamina": 50,
    "eitr": 0,
    "duration": 20,
    "healing": 1,
    "weight": 10,
    "stack_size": 10,
    "biome": "늪지대",
    "station": "가마솥 [2]",
    "eng_name": "Muckshake",
    "img": "img/foods/10.png"
  },
  {
    "id": 11,
    "name": "순무스튜",
    "type": "Yellow",
    "health": 18,
    "stamina": 55,
    "eitr": 0,
    "duration": 25,
    "healing": 2,
    "weight": 10,
    "stack_size": 10,
    "biome": "늪지대",
    "station": "가마솥 [2]",
    "eng_name": "Turnip stew",
    "img": "img/foods/11.png"
  },
  {
    "id": 12,
    "name": "소시지",
    "type": "Red",
    "health": 55,
    "stamina": 18,
    "eitr": 0,
    "duration": 25,
    "healing": 3,
    "weight": 5,
    "stack_size": 20,
    "biome": "늪지대",
    "station": "가마솥 [2]",
    "eng_name": "Sausages",
    "img": "img/foods/12.png"
  },
  {
    "id": 13,
    "name": "블랙스프",
    "type": "Red",
    "health": 50,
    "stamina": 17,
    "eitr": 0,
    "duration": 20,
    "healing": 3,
    "weight": 10,
    "stack_size": 10,
    "biome": "늪지대",
    "station": "가마솥 [2]",
    "eng_name": "Black soup",
    "img": "img/foods/13.png"
  },
  {
    "id": 14,
    "name": "Whole roasted Meadow boar",
    "type": "White",
    "health": 35,
    "stamina": 35,
    "eitr": 0,
    "duration": 50,
    "healing": 2,
    "weight": 100,
    "stack_size": 5,
    "biome": "늪지대",
    "station": "Food preparation table",
    "eng_name": "Whole roasted Meadow boar",
    "img": "img/foods/14.png"
  },
  {
    "id": 15,
    "name": "Black Forest buffet platter",
    "type": "White",
    "health": 35,
    "stamina": 35,
    "eitr": 0,
    "duration": 50,
    "healing": 3,
    "weight": 100,
    "stack_size": 5,
    "biome": "늪지대",
    "station": "Food preparation table",
    "eng_name": "Black Forest buffet platter",
    "img": "img/foods/15.png"
  },
  {
    "id": 16,
    "name": "Swamp dweller's delight",
    "type": "White",
    "health": 35,
    "stamina": 35,
    "eitr": 0,
    "duration": 50,
    "healing": 3,
    "weight": 100,
    "stack_size": 5,
    "biome": "늪지대",
    "station": "Food preparation table",
    "eng_name": "Swamp dweller's delight",
    "img": "img/foods/16.png"
  },
  {
    "id": 17,
    "name": "요리한 바다뱀고기",
    "type": "Red",
    "health": 70,
    "stamina": 23,
    "eitr": 0,
    "duration": 25,
    "healing": 3,
    "weight": 100,
    "stack_size": 50,
    "biome": "늪지대",
    "station": "Iron cooking station",
    "eng_name": "Cooked serpent meat",
    "img": "img/foods/17.png"
  },
  {
    "id": 18,
    "name": "바다뱀스튜",
    "type": "Red",
    "health": 80,
    "stamina": 26,
    "eitr": 0,
    "duration": 30,
    "healing": 4,
    "weight": 10,
    "stack_size": 10,
    "biome": "늪지대",
    "station": "가마솥 [2]",
    "eng_name": "Serpent stew",
    "img": "img/foods/18.png"
  },
  {
    "id": 19,
    "name": "Sailor's bounty",
    "type": "White",
    "health": 45,
    "stamina": 45,
    "eitr": 0,
    "duration": 50,
    "healing": 3,
    "weight": 100,
    "stack_size": 5,
    "biome": "늪지대",
    "station": "Food preparation table",
    "eng_name": "Sailor's bounty",
    "img": "img/foods/19.png"
  },
  {
    "id": 20,
    "name": "양파스프",
    "type": "Yellow",
    "health": 20,
    "stamina": 60,
    "eitr": 0,
    "duration": 20,
    "healing": 1,
    "weight": 10,
    "stack_size": 10,
    "biome": "산",
    "station": "가마솥 [3]",
    "eng_name": "Onion soup",
    "img": "img/foods/20.png"
  },
  {
    "id": 21,
    "name": "요리한 늑대고기",
    "type": "Red",
    "health": 45,
    "stamina": 15,
    "eitr": 0,
    "duration": 20,
    "healing": 3,
    "weight": 10,
    "stack_size": 20,
    "biome": "산",
    "station": "Cooking station",
    "eng_name": "Cooked wolf meat",
    "img": "img/foods/21.png"
  },
  {
    "id": 22,
    "name": "늑대육포",
    "type": "White",
    "health": 33,
    "stamina": 33,
    "eitr": 0,
    "duration": 30,
    "healing": 3,
    "weight": 5,
    "stack_size": 20,
    "biome": "산",
    "station": "가마솥 [3]",
    "eng_name": "Wolf jerky",
    "img": "img/foods/22.png"
  },
  {
    "id": 23,
    "name": "늑대꼬치",
    "type": "Red",
    "health": 65,
    "stamina": 21,
    "eitr": 0,
    "duration": 25,
    "healing": 3,
    "weight": 5,
    "stack_size": 20,
    "biome": "산",
    "station": "가마솥 [3]",
    "eng_name": "Wolf skewer",
    "img": "img/foods/23.png"
  },
  {
    "id": 24,
    "name": "아이즈크림",
    "type": "Yellow",
    "health": 21,
    "stamina": 65,
    "eitr": 0,
    "duration": 25,
    "healing": 1,
    "weight": 5,
    "stack_size": 10,
    "biome": "산",
    "station": "가마솥 [3]",
    "eng_name": "Eyescream",
    "img": "img/foods/24.png"
  },
  {
    "id": 25,
    "name": "Hearty Mountain logger's stew",
    "type": "White",
    "health": 45,
    "stamina": 45,
    "eitr": 0,
    "duration": 50,
    "healing": 3,
    "weight": 100,
    "stack_size": 5,
    "biome": "산",
    "station": "Food preparation table",
    "eng_name": "Hearty Mountain logger's stew",
    "img": "img/foods/25.png"
  },
  {
    "id": 26,
    "name": "요리한 록스고기",
    "type": "Red",
    "health": 50,
    "stamina": 16,
    "eitr": 0,
    "duration": 20,
    "healing": 4,
    "weight": 10,
    "stack_size": 20,
    "biome": "평원",
    "station": "Iron cooking station",
    "eng_name": "Cooked lox meat",
    "img": "img/foods/26.png"
  },
  {
    "id": 27,
    "name": "피쉬랩",
    "type": "Red",
    "health": 70,
    "stamina": 23,
    "eitr": 0,
    "duration": 25,
    "healing": 4,
    "weight": 10,
    "stack_size": 10,
    "biome": "평원",
    "station": "가마솥 [4]",
    "eng_name": "Fish wraps",
    "img": "img/foods/27.png"
  },
  {
    "id": 28,
    "name": "록스고기파이",
    "type": "Red",
    "health": 75,
    "stamina": 24,
    "eitr": 0,
    "duration": 30,
    "healing": 4,
    "weight": 10,
    "stack_size": 10,
    "biome": "평원",
    "station": "Food preparation table",
    "eng_name": "Lox meat pie",
    "img": "img/foods/28.png"
  },
  {
    "id": 29,
    "name": "블랙푸딩",
    "type": "Yellow",
    "health": 25,
    "stamina": 75,
    "eitr": 0,
    "duration": 30,
    "healing": 2,
    "weight": 10,
    "stack_size": 10,
    "biome": "평원",
    "station": "가마솥 [4]",
    "eng_name": "Blood pudding",
    "img": "img/foods/29.png"
  },
  {
    "id": 30,
    "name": "빵",
    "type": "Yellow",
    "health": 23,
    "stamina": 70,
    "eitr": 0,
    "duration": 25,
    "healing": 2,
    "weight": 5,
    "stack_size": 20,
    "biome": "평원",
    "station": "Food preparation table",
    "eng_name": "Bread",
    "img": "img/foods/30.png"
  },
  {
    "id": 31,
    "name": "Plains pie picnic",
    "type": "White",
    "health": 55,
    "stamina": 55,
    "eitr": 0,
    "duration": 50,
    "healing": 4,
    "weight": 100,
    "stack_size": 5,
    "biome": "평원",
    "station": "Food preparation table",
    "eng_name": "Plains pie picnic",
    "img": "img/foods/31.png"
  },
  {
    "id": 32,
    "name": "요리한 달걀",
    "type": "Red",
    "health": 35,
    "stamina": 12,
    "eitr": 0,
    "duration": 20,
    "healing": 2,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "가마솥 [1]",
    "eng_name": "Cooked egg",
    "img": "img/foods/32.png"
  },
  {
    "id": 33,
    "name": "요리한 추적자고기",
    "type": "Red",
    "health": 60,
    "stamina": 20,
    "eitr": 0,
    "duration": 20,
    "healing": 5,
    "weight": 10,
    "stack_size": 20,
    "biome": "안개지대",
    "station": "Iron cooking station",
    "eng_name": "Cooked seeker meat",
    "img": "img/foods/33.png"
  },
  {
    "id": 34,
    "name": "요리한 토끼고기",
    "type": "Red",
    "health": 60,
    "stamina": 20,
    "eitr": 0,
    "duration": 20,
    "healing": 5,
    "weight": 10,
    "stack_size": 20,
    "biome": "안개지대",
    "station": "Iron cooking station",
    "eng_name": "Cooked hare meat",
    "img": "img/foods/34.png"
  },
  {
    "id": 35,
    "name": "요리한 닭고기",
    "type": "Red",
    "health": 60,
    "stamina": 20,
    "eitr": 0,
    "duration": 20,
    "healing": 5,
    "weight": 10,
    "stack_size": 20,
    "biome": "안개지대",
    "station": "Iron cooking station",
    "eng_name": "Cooked chicken meat",
    "img": "img/foods/35.png"
  },
  {
    "id": 36,
    "name": "고기모듬",
    "type": "Red",
    "health": 80,
    "stamina": 26,
    "eitr": 0,
    "duration": 30,
    "healing": 5,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "Food preparation table",
    "eng_name": "Meat platter",
    "img": "img/foods/36.png"
  },
  {
    "id": 37,
    "name": "꿀맛바삭치킨",
    "type": "Red",
    "health": 80,
    "stamina": 26,
    "eitr": 0,
    "duration": 30,
    "healing": 5,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "Food preparation table",
    "eng_name": "Honey glazed chicken",
    "img": "img/foods/37.png"
  },
  {
    "id": 38,
    "name": "안개토끼슈프림",
    "type": "Red",
    "health": 85,
    "stamina": 28,
    "eitr": 0,
    "duration": 25,
    "healing": 5,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "Food preparation table",
    "eng_name": "Misthare supreme",
    "img": "img/foods/38.png"
  },
  {
    "id": 39,
    "name": "샐러드",
    "type": "Yellow",
    "health": 26,
    "stamina": 80,
    "eitr": 0,
    "duration": 25,
    "healing": 3,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "가마솥 [5]",
    "eng_name": "Salad",
    "img": "img/foods/39.png"
  },
  {
    "id": 40,
    "name": "버섯오믈렛",
    "type": "Yellow",
    "health": 28,
    "stamina": 85,
    "eitr": 0,
    "duration": 25,
    "healing": 3,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "가마솥 [5]",
    "eng_name": "Mushroom omelette",
    "img": "img/foods/40.png"
  },
  {
    "id": 41,
    "name": "피쉬앤브레드",
    "type": "Yellow",
    "health": 30,
    "stamina": 90,
    "eitr": 0,
    "duration": 30,
    "healing": 3,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "Food preparation table",
    "eng_name": "Fish 'n' bread",
    "img": "img/foods/41.png"
  },
  {
    "id": 42,
    "name": "속채운버섯",
    "type": "Blue",
    "health": 25,
    "stamina": 12,
    "eitr": 75,
    "duration": 25,
    "healing": 3,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "Food preparation table",
    "eng_name": "Stuffed mushroom",
    "img": "img/foods/42.png"
  },
  {
    "id": 43,
    "name": "이그드라실죽",
    "type": "Blue",
    "health": 27,
    "stamina": 13,
    "eitr": 80,
    "duration": 25,
    "healing": 3,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "가마솥 [5]",
    "eng_name": "Yggdrasil porridge",
    "img": "img/foods/43.png"
  },
  {
    "id": 44,
    "name": "추적자아스픽",
    "type": "Blue",
    "health": 28,
    "stamina": 14,
    "eitr": 85,
    "duration": 30,
    "healing": 3,
    "weight": 10,
    "stack_size": 10,
    "biome": "안개지대",
    "station": "가마솥 [5]",
    "eng_name": "Seeker aspic",
    "img": "img/foods/44.png"
  },
  {
    "id": 45,
    "name": "Mushrooms galore á la Mistlands",
    "type": "White",
    "health": 65,
    "stamina": 65,
    "eitr": 33,
    "duration": 50,
    "healing": 5,
    "weight": 100,
    "stack_size": 5,
    "biome": "안개지대",
    "station": "Food preparation table",
    "eng_name": "Mushrooms galore á la Mistlands",
    "img": "img/foods/45.png"
  },
  {
    "id": 46,
    "name": "요리한 애스크스빈꼬리",
    "type": "Red",
    "health": 70,
    "stamina": 24,
    "eitr": 0,
    "duration": 20,
    "healing": 6,
    "weight": 10,
    "stack_size": 20,
    "biome": "잿가루지대",
    "station": "Iron cooking station",
    "eng_name": "Cooked asksvin tail",
    "img": "img/foods/46.png"
  },
  {
    "id": 47,
    "name": "요리한 화산매고기",
    "type": "Red",
    "health": 70,
    "stamina": 24,
    "eitr": 0,
    "duration": 20,
    "healing": 6,
    "weight": 10,
    "stack_size": 20,
    "biome": "잿가루지대",
    "station": "Iron cooking station",
    "eng_name": "Cooked volture meat",
    "img": "img/foods/47.png"
  },
  {
    "id": 48,
    "name": "요리한 뼈주둥이고기",
    "type": "Red",
    "health": 90,
    "stamina": 30,
    "eitr": 0,
    "duration": 25,
    "healing": 6,
    "weight": 100,
    "stack_size": 50,
    "biome": "잿가루지대",
    "station": "Iron cooking station",
    "eng_name": "Cooked bonemaw meat",
    "img": "img/foods/48.png"
  },
  {
    "id": 49,
    "name": "불맛스빈스튜",
    "type": "Red",
    "health": 95,
    "stamina": 32,
    "eitr": 0,
    "duration": 25,
    "healing": 6,
    "weight": 10,
    "stack_size": 10,
    "biome": "잿가루지대",
    "station": "가마솥 [5]",
    "eng_name": "Fiery svinstew",
    "img": "img/foods/49.png"
  },
  {
    "id": 50,
    "name": "으깬고기",
    "type": "Red",
    "health": 100,
    "stamina": 34,
    "eitr": 0,
    "duration": 25,
    "healing": 6,
    "weight": 10,
    "stack_size": 10,
    "biome": "잿가루지대",
    "station": "가마솥 [6]",
    "eng_name": "Mashed meat",
    "img": "img/foods/50.png"
  },
  {
    "id": 51,
    "name": "새콤파이",
    "type": "Red",
    "health": 105,
    "stamina": 35,
    "eitr": 0,
    "duration": 30,
    "healing": 6,
    "weight": 10,
    "stack_size": 10,
    "biome": "잿가루지대",
    "station": "Food preparation table",
    "eng_name": "Piquant pie",
    "img": "img/foods/51.png"
  },
  {
    "id": 52,
    "name": "매콤마멀레이드",
    "type": "Yellow",
    "health": 30,
    "stamina": 90,
    "eitr": 0,
    "duration": 25,
    "healing": 4,
    "weight": 10,
    "stack_size": 10,
    "biome": "잿가루지대",
    "station": "가마솥 [5]",
    "eng_name": "Spicy marmalade",
    "img": "img/foods/52.png"
  },
  {
    "id": 53,
    "name": "맹화의메들리",
    "type": "Yellow",
    "health": 32,
    "stamina": 95,
    "eitr": 0,
    "duration": 25,
    "healing": 4,
    "weight": 10,
    "stack_size": 10,
    "biome": "잿가루지대",
    "station": "가마솥 [6]",
    "eng_name": "Scorching medley",
    "img": "img/foods/53.png"
  },
  {
    "id": 54,
    "name": "크러스트파이",
    "type": "Yellow",
    "health": 34,
    "stamina": 100,
    "eitr": 0,
    "duration": 30,
    "healing": 4,
    "weight": 10,
    "stack_size": 10,
    "biome": "잿가루지대",
    "station": "Food preparation table",
    "eng_name": "Roasted crust pie",
    "img": "img/foods/54.png"
  },
  {
    "id": 55,
    "name": "Sizzling berry broth",
    "type": "Blue",
    "health": 28,
    "stamina": 14,
    "eitr": 85,
    "duration": 25,
    "healing": 4,
    "weight": 10,
    "stack_size": 10,
    "biome": "잿가루지대",
    "station": "가마솥 [5]",
    "eng_name": "Sizzling berry broth",
    "img": "img/foods/55.png"
  },
  {
    "id": 56,
    "name": "스파클링 버섯쉐이크",
    "type": "Blue",
    "health": 30,
    "stamina": 15,
    "eitr": 90,
    "duration": 25,
    "healing": 4,
    "weight": 10,
    "stack_size": 10,
    "biome": "잿가루지대",
    "station": "가마솥 [6]",
    "eng_name": "Sparkling shroomshake",
    "img": "img/foods/56.png"
  },
  {
    "id": 57,
    "name": "Marinated greens",
    "type": "Blue",
    "health": 32,
    "stamina": 16,
    "eitr": 95,
    "duration": 30,
    "healing": 4,
    "weight": 10,
    "stack_size": 10,
    "biome": "잿가루지대",
    "station": "가마솥 [6]",
    "eng_name": "Marinated greens",
    "img": "img/foods/57.png"
  },
  {
    "id": 58,
    "name": "Ashlands gourmet bowl",
    "type": "White",
    "health": 75,
    "stamina": 75,
    "eitr": 38,
    "duration": 50,
    "healing": 6,
    "weight": 100,
    "stack_size": 5,
    "biome": "잿가루지대",
    "station": "Food preparation table",
    "eng_name": "Ashlands gourmet bowl",
    "img": "img/foods/58.png"
  }
]