itemList =     
[
    {
        "id" : 1,
        "name" : "구운 넥꼬리",
        "type" : "Red",
        "health" : 25,
        "stamina" : 8,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 2,
        "weight" : 5,
        "stack_size" : 20,
        "biome" : "목초지",
        "station" : "Cooking station",
        "eng_name" : "Grilled neck tail",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/0\/06\/Grilled_neck_tail.png\/revision\/latest?cb=20210215131743"
    },
    {
        "id" : 2,
        "name" : "요리한 멧돼지고기",
        "type" : "Red",
        "health" : 30,
        "stamina" : 10,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 2,
        "weight" : 10,
        "stack_size" : 20,
        "biome" : "목초지",
        "station" : "Cooking station",
        "eng_name" : "Cooked boar meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/0\/01\/Cooked_boar_meat.png\/revision\/latest?cb=20211222210540"
    },
    {
        "id" : 3,
        "name" : "요리한 사슴고기",
        "type" : "Red",
        "health" : 35,
        "stamina" : 12,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 2,
        "weight" : 10,
        "stack_size" : 20,
        "biome" : "목초지",
        "station" : "Cooking station",
        "eng_name" : "Cooked deer meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/b\/bc\/Cooked_deer_meat.png\/revision\/latest?cb=20210922034153"
    },
    {
        "id" : 4,
        "name" : "멧돼지육포",
        "type" : "White",
        "health" : 23,
        "stamina" : 23,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 2,
        "weight" : 5,
        "stack_size" : 20,
        "biome" : "검은숲",
        "station" : "가마솥 [1]",
        "eng_name" : "Boar jerky",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/1\/14\/Boar_jerky.png\/revision\/latest?cb=20210927004543"
    },
    {
        "id" : 5,
        "name" : "다진고기소스",
        "type" : "Red",
        "health" : 40,
        "stamina" : 13,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "검은숲",
        "station" : "가마솥 [1]",
        "eng_name" : "Minced meat sauce",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/4\/4d\/Minced_meat_sauce.png\/revision\/latest?cb=20210922034153"
    },
    {
        "id" : 6,
        "name" : "여왕의잼",
        "type" : "Yellow",
        "health" : 14,
        "stamina" : 40,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 2,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "검은숲",
        "station" : "가마솥 [1]",
        "eng_name" : "Queen's jam",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/5\/5a\/Queen%27s_jam.png\/revision\/latest?cb=20210215131812"
    },
    {
        "id" : 7,
        "name" : "당근스프",
        "type" : "Yellow",
        "health" : 15,
        "stamina" : 45,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 2,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "검은숲",
        "station" : "가마솥 [1]",
        "eng_name" : "Carrot soup",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/0\/00\/Carrot_soup.png\/revision\/latest?cb=20210215131443"
    },
    {
        "id" : 8,
        "name" : "사슴스튜",
        "type" : "Red",
        "health" : 45,
        "stamina" : 15,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "검은숲",
        "station" : "가마솥 [1]",
        "eng_name" : "Deer stew",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/b\/bf\/Deerstew.png\/revision\/latest?cb=20210922034153"
    },
    {
        "id" : 9,
        "name" : "요리한 생선",
        "type" : "Red",
        "health" : 45,
        "stamina" : 15,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 2,
        "weight" : 5,
        "stack_size" : 20,
        "biome" : "늪지대",
        "station" : "Cooking station",
        "eng_name" : "Cooked fish",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/1\/16\/Cooked_fish.png\/revision\/latest?cb=20210215131603"
    },
    {
        "id" : 10,
        "name" : "먹셰이크",
        "type" : "Yellow",
        "health" : 16,
        "stamina" : 50,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 1,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "늪지대",
        "station" : "가마솥 [2]",
        "eng_name" : "Muckshake",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/1\/1d\/Shocklatesmoothie.png\/revision\/latest?cb=20210922034153"
    },
    {
        "id" : 11,
        "name" : "순무스튜",
        "type" : "Yellow",
        "health" : 18,
        "stamina" : 55,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 2,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "늪지대",
        "station" : "가마솥 [2]",
        "eng_name" : "Turnip stew",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/f\/fd\/Turnip_stew.png\/revision\/latest?cb=20210212175937"
    },
    {
        "id" : 12,
        "name" : "소시지",
        "type" : "Red",
        "health" : 55,
        "stamina" : 18,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 3,
        "weight" : 5,
        "stack_size" : 20,
        "biome" : "늪지대",
        "station" : "가마솥 [2]",
        "eng_name" : "Sausages",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/a\/a0\/Sausages.png\/revision\/latest?cb=20210215131836"
    },
    {
        "id" : 13,
        "name" : "블랙스프",
        "type" : "Red",
        "health" : 50,
        "stamina" : 17,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "늪지대",
        "station" : "가마솥 [2]",
        "eng_name" : "Black soup",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/e\/e6\/BlackSoup.png\/revision\/latest?cb=20210922034152"
    },
    {
        "id" : 14,
        "name" : "Whole roasted Meadow boar",
        "type" : "White",
        "health" : 35,
        "stamina" : 35,
        "eitr" : 0,
        "duration" : 50,
        "healing" : 2,
        "weight" : 100,
        "stack_size" : 5,
        "biome" : "늪지대",
        "station" : "Food preparation table",
        "eng_name" : "Whole roasted Meadow boar",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/c\/c7\/Whole_roasted_Meadow_boar.png\/revision\/latest?cb=20241019120434"
    },
    {
        "id" : 15,
        "name" : "Black Forest buffet platter",
        "type" : "White",
        "health" : 35,
        "stamina" : 35,
        "eitr" : 0,
        "duration" : 50,
        "healing" : 3,
        "weight" : 100,
        "stack_size" : 5,
        "biome" : "늪지대",
        "station" : "Food preparation table",
        "eng_name" : "Black Forest buffet platter",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/d\/df\/Black_Forest_buffet_platter.png\/revision\/latest?cb=20241019120544"
    },
    {
        "id" : 16,
        "name" : "Swamp dweller's delight",
        "type" : "White",
        "health" : 35,
        "stamina" : 35,
        "eitr" : 0,
        "duration" : 50,
        "healing" : 3,
        "weight" : 100,
        "stack_size" : 5,
        "biome" : "늪지대",
        "station" : "Food preparation table",
        "eng_name" : "Swamp dweller's delight",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/d\/d9\/Swamp_dweller%27s_delight.png\/revision\/latest?cb=20241019120609"
    },
    {
        "id" : 17,
        "name" : "요리한 바다뱀고기",
        "type" : "Red",
        "health" : 70,
        "stamina" : 23,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 3,
        "weight" : 100,
        "stack_size" : 50,
        "biome" : "늪지대",
        "station" : "Iron cooking station",
        "eng_name" : "Cooked serpent meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/c\/c1\/Cooked_serpent_meat.png\/revision\/latest?cb=20210215131841"
    },
    {
        "id" : 18,
        "name" : "바다뱀스튜",
        "type" : "Red",
        "health" : 80,
        "stamina" : 26,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "늪지대",
        "station" : "가마솥 [2]",
        "eng_name" : "Serpent stew",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/5\/55\/Serpent_stew.png\/revision\/latest?cb=20210215131844"
    },
    {
        "id" : 19,
        "name" : "Sailor's bounty",
        "type" : "White",
        "health" : 45,
        "stamina" : 45,
        "eitr" : 0,
        "duration" : 50,
        "healing" : 3,
        "weight" : 100,
        "stack_size" : 5,
        "biome" : "늪지대",
        "station" : "Food preparation table",
        "eng_name" : "Sailor's bounty",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/9\/94\/Sailor%27s_bounty.png\/revision\/latest?cb=20241019134010"
    },
    {
        "id" : 20,
        "name" : "양파스프",
        "type" : "Yellow",
        "health" : 20,
        "stamina" : 60,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 1,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "산",
        "station" : "가마솥 [3]",
        "eng_name" : "Onion soup",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/7\/72\/OnionSoup.png\/revision\/latest?cb=20210922034153"
    },
    {
        "id" : 21,
        "name" : "요리한 늑대고기",
        "type" : "Red",
        "health" : 45,
        "stamina" : 15,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 20,
        "biome" : "산",
        "station" : "Cooking station",
        "eng_name" : "Cooked wolf meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/d\/dc\/Cooked_wolf_meat.png\/revision\/latest?cb=20210928173121"
    },
    {
        "id" : 22,
        "name" : "늑대육포",
        "type" : "White",
        "health" : 33,
        "stamina" : 33,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 3,
        "weight" : 5,
        "stack_size" : 20,
        "biome" : "산",
        "station" : "가마솥 [3]",
        "eng_name" : "Wolf jerky",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/3\/30\/Wolf_jerky.png\/revision\/latest?cb=20210922034153"
    },
    {
        "id" : 23,
        "name" : "늑대꼬치",
        "type" : "Red",
        "health" : 65,
        "stamina" : 21,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 3,
        "weight" : 5,
        "stack_size" : 20,
        "biome" : "산",
        "station" : "가마솥 [3]",
        "eng_name" : "Wolf skewer",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/d\/d7\/Wolf_skewer.png\/revision\/latest?cb=20210922034153"
    },
    {
        "id" : 24,
        "name" : "아이즈크림",
        "type" : "Yellow",
        "health" : 21,
        "stamina" : 65,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 1,
        "weight" : 5,
        "stack_size" : 10,
        "biome" : "산",
        "station" : "가마솥 [3]",
        "eng_name" : "Eyescream",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/9\/90\/Eyescream.png\/revision\/latest?cb=20210922034153"
    },
    {
        "id" : 25,
        "name" : "Hearty Mountain logger's stew",
        "type" : "White",
        "health" : 45,
        "stamina" : 45,
        "eitr" : 0,
        "duration" : 50,
        "healing" : 3,
        "weight" : 100,
        "stack_size" : 5,
        "biome" : "산",
        "station" : "Food preparation table",
        "eng_name" : "Hearty Mountain logger's stew",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/a\/a0\/Hearty_Mountain_logger%27s_stew.png\/revision\/latest?cb=20241019134031"
    },
    {
        "id" : 26,
        "name" : "요리한 록스고기",
        "type" : "Red",
        "health" : 50,
        "stamina" : 16,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 20,
        "biome" : "평원",
        "station" : "Iron cooking station",
        "eng_name" : "Cooked lox meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/4\/40\/Cooked_lox_meat.png\/revision\/latest?cb=20210215131722"
    },
    {
        "id" : 27,
        "name" : "피쉬랩",
        "type" : "Red",
        "health" : 70,
        "stamina" : 23,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "평원",
        "station" : "가마솥 [4]",
        "eng_name" : "Fish wraps",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/b\/b5\/Fish_wraps.png\/revision\/latest?cb=20210215131607"
    },
    {
        "id" : 28,
        "name" : "록스고기파이",
        "type" : "Red",
        "health" : 75,
        "stamina" : 24,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "평원",
        "station" : "Food preparation table",
        "eng_name" : "Lox meat pie",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/5\/5e\/Lox_meat_pie.png\/revision\/latest?cb=20210215131724"
    },
    {
        "id" : 29,
        "name" : "블랙푸딩",
        "type" : "Yellow",
        "health" : 25,
        "stamina" : 75,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 2,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "평원",
        "station" : "가마솥 [4]",
        "eng_name" : "Blood pudding",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/2\/28\/Blood_pudding.png\/revision\/latest?cb=20210215131359"
    },
    {
        "id" : 30,
        "name" : "빵",
        "type" : "Yellow",
        "health" : 23,
        "stamina" : 70,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 2,
        "weight" : 5,
        "stack_size" : 20,
        "biome" : "평원",
        "station" : "Food preparation table",
        "eng_name" : "Bread",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/e\/e1\/Bread.png\/revision\/latest?cb=20210215131421"
    },
    {
        "id" : 31,
        "name" : "Plains pie picnic",
        "type" : "White",
        "health" : 55,
        "stamina" : 55,
        "eitr" : 0,
        "duration" : 50,
        "healing" : 4,
        "weight" : 100,
        "stack_size" : 5,
        "biome" : "평원",
        "station" : "Food preparation table",
        "eng_name" : "Plains pie picnic",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/2\/21\/Plains_pie_picnic.png\/revision\/latest?cb=20241019134111"
    },
    {
        "id" : 32,
        "name" : "요리한 달걀",
        "type" : "Red",
        "health" : 35,
        "stamina" : 12,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 2,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "가마솥 [1]",
        "eng_name" : "Cooked egg",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/a\/ae\/Cooked_egg.png\/revision\/latest?cb=20221130075934"
    },
    {
        "id" : 33,
        "name" : "요리한 추적자고기",
        "type" : "Red",
        "health" : 60,
        "stamina" : 20,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 5,
        "weight" : 10,
        "stack_size" : 20,
        "biome" : "안개지대",
        "station" : "Iron cooking station",
        "eng_name" : "Cooked seeker meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/5\/5c\/Cooked_seeker_meat.png\/revision\/latest?cb=20221130105204"
    },
    {
        "id" : 34,
        "name" : "요리한 토끼고기",
        "type" : "Red",
        "health" : 60,
        "stamina" : 20,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 5,
        "weight" : 10,
        "stack_size" : 20,
        "biome" : "안개지대",
        "station" : "Iron cooking station",
        "eng_name" : "Cooked hare meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/2\/2b\/Cooked_hare_meat.png\/revision\/latest?cb=20221130140344"
    },
    {
        "id" : 35,
        "name" : "요리한 닭고기",
        "type" : "Red",
        "health" : 60,
        "stamina" : 20,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 5,
        "weight" : 10,
        "stack_size" : 20,
        "biome" : "안개지대",
        "station" : "Iron cooking station",
        "eng_name" : "Cooked chicken meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/4\/4a\/Cooked_chicken_meat.png\/revision\/latest?cb=20221130104358"
    },
    {
        "id" : 36,
        "name" : "고기모듬",
        "type" : "Red",
        "health" : 80,
        "stamina" : 26,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 5,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "Food preparation table",
        "eng_name" : "Meat platter",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/8\/85\/Meat_platter.png\/revision\/latest?cb=20221125173026"
    },
    {
        "id" : 37,
        "name" : "꿀맛바삭치킨",
        "type" : "Red",
        "health" : 80,
        "stamina" : 26,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 5,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "Food preparation table",
        "eng_name" : "Honey glazed chicken",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/9\/9f\/Honey_glazed_chicken.png\/revision\/latest?cb=20221209094423"
    },
    {
        "id" : 38,
        "name" : "안개토끼슈프림",
        "type" : "Red",
        "health" : 85,
        "stamina" : 28,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 5,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "Food preparation table",
        "eng_name" : "Misthare supreme",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/a\/a1\/Misthare_supreme.png\/revision\/latest?cb=20221125173027"
    },
    {
        "id" : 39,
        "name" : "샐러드",
        "type" : "Yellow",
        "health" : 26,
        "stamina" : 80,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "가마솥 [5]",
        "eng_name" : "Salad",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/7\/7e\/Salad.png\/revision\/latest?cb=20221125173029"
    },
    {
        "id" : 40,
        "name" : "버섯오믈렛",
        "type" : "Yellow",
        "health" : 28,
        "stamina" : 85,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "가마솥 [5]",
        "eng_name" : "Mushroom omelette",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/7\/7b\/Mushroom_omelette.png\/revision\/latest?cb=20221125173028"
    },
    {
        "id" : 41,
        "name" : "피쉬앤브레드",
        "type" : "Yellow",
        "health" : 30,
        "stamina" : 90,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "Food preparation table",
        "eng_name" : "Fish 'n' bread",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/2\/2c\/Fish_%27n%27_bread.png\/revision\/latest?cb=20221130101653"
    },
    {
        "id" : 42,
        "name" : "속채운버섯",
        "type" : "Blue",
        "health" : 25,
        "stamina" : 12,
        "eitr" : 75,
        "duration" : 25,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "Food preparation table",
        "eng_name" : "Stuffed mushroom",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/7\/75\/Stuffed_mushroom.png\/revision\/latest?cb=20221125173031"
    },
    {
        "id" : 43,
        "name" : "이그드라실죽",
        "type" : "Blue",
        "health" : 27,
        "stamina" : 13,
        "eitr" : 80,
        "duration" : 25,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "가마솥 [5]",
        "eng_name" : "Yggdrasil porridge",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/e\/e1\/Yggdrasil_porridge.png\/revision\/latest?cb=20221125173034"
    },
    {
        "id" : 44,
        "name" : "추적자아스픽",
        "type" : "Blue",
        "health" : 28,
        "stamina" : 14,
        "eitr" : 85,
        "duration" : 30,
        "healing" : 3,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "안개지대",
        "station" : "가마솥 [5]",
        "eng_name" : "Seeker aspic",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/1\/1a\/Seeker_aspic.png\/revision\/latest?cb=20221125173030"
    },
    {
        "id" : 45,
        "name" : "Mushrooms galore á la Mistlands",
        "type" : "White",
        "health" : 65,
        "stamina" : 65,
        "eitr" : 33,
        "duration" : 50,
        "healing" : 5,
        "weight" : 100,
        "stack_size" : 5,
        "biome" : "안개지대",
        "station" : "Food preparation table",
        "eng_name" : "Mushrooms galore á la Mistlands",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/f\/f3\/Mushrooms_galore_%C3%A1_la_Mistlands.png\/revision\/latest?cb=20241019134321"
    },
    {
        "id" : 46,
        "name" : "요리한 애스크스빈꼬리",
        "type" : "Red",
        "health" : 70,
        "stamina" : 24,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 6,
        "weight" : 10,
        "stack_size" : 20,
        "biome" : "잿가루지대",
        "station" : "Iron cooking station",
        "eng_name" : "Cooked asksvin tail",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/c\/ce\/Cooked_asksvin_tail.png\/revision\/latest?cb=20240423111445"
    },
    {
        "id" : 47,
        "name" : "요리한 화산매고기",
        "type" : "Red",
        "health" : 70,
        "stamina" : 24,
        "eitr" : 0,
        "duration" : 20,
        "healing" : 6,
        "weight" : 10,
        "stack_size" : 20,
        "biome" : "잿가루지대",
        "station" : "Iron cooking station",
        "eng_name" : "Cooked volture meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/3\/30\/Cooked_volture_meat.png\/revision\/latest?cb=20240423111702"
    },
    {
        "id" : 48,
        "name" : "요리한 뼈주둥이고기",
        "type" : "Red",
        "health" : 90,
        "stamina" : 30,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 6,
        "weight" : 100,
        "stack_size" : 50,
        "biome" : "잿가루지대",
        "station" : "Iron cooking station",
        "eng_name" : "Cooked bonemaw meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/b\/b6\/Cooked_bonemaw_meat.png\/revision\/latest?cb=20240423111538"
    },
    {
        "id" : 49,
        "name" : "불맛스빈스튜",
        "type" : "Red",
        "health" : 95,
        "stamina" : 32,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 6,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "잿가루지대",
        "station" : "가마솥 [5]",
        "eng_name" : "Fiery svinstew",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/9\/90\/Fiery_svinstew.png\/revision\/latest?cb=20240423123219"
    },
    {
        "id" : 50,
        "name" : "으깬고기",
        "type" : "Red",
        "health" : 100,
        "stamina" : 34,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 6,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "잿가루지대",
        "station" : "가마솥 [6]",
        "eng_name" : "Mashed meat",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/4\/47\/Mashed_meat.png\/revision\/latest?cb=20240423124050"
    },
    {
        "id" : 51,
        "name" : "새콤파이",
        "type" : "Red",
        "health" : 105,
        "stamina" : 35,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 6,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "잿가루지대",
        "station" : "Food preparation table",
        "eng_name" : "Piquant pie",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/b\/b5\/Piquant_pie.png\/revision\/latest?cb=20240423130343"
    },
    {
        "id" : 52,
        "name" : "매콤마멀레이드",
        "type" : "Yellow",
        "health" : 30,
        "stamina" : 90,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "잿가루지대",
        "station" : "가마솥 [5]",
        "eng_name" : "Spicy marmalade",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/e\/e2\/Spicy_marmalade.png\/revision\/latest?cb=20240423132525"
    },
    {
        "id" : 53,
        "name" : "맹화의메들리",
        "type" : "Yellow",
        "health" : 32,
        "stamina" : 95,
        "eitr" : 0,
        "duration" : 25,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "잿가루지대",
        "station" : "가마솥 [6]",
        "eng_name" : "Scorching medley",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/3\/30\/Scorching_medley.png\/revision\/latest?cb=20240423131728"
    },
    {
        "id" : 54,
        "name" : "크러스트파이",
        "type" : "Yellow",
        "health" : 34,
        "stamina" : 100,
        "eitr" : 0,
        "duration" : 30,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "잿가루지대",
        "station" : "Food preparation table",
        "eng_name" : "Roasted crust pie",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/f\/f4\/Roasted_crust_pie.png\/revision\/latest?cb=20240423131035"
    },
    {
        "id" : 55,
        "name" : "Sizzling berry broth",
        "type" : "Blue",
        "health" : 28,
        "stamina" : 14,
        "eitr" : 85,
        "duration" : 25,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "잿가루지대",
        "station" : "가마솥 [5]",
        "eng_name" : "Sizzling berry broth",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/7\/7d\/Sizzling_berry_broth.png\/revision\/latest?cb=20240423132358"
    },
    {
        "id" : 56,
        "name" : "스파클링 버섯쉐이크",
        "type" : "Blue",
        "health" : 30,
        "stamina" : 15,
        "eitr" : 90,
        "duration" : 25,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "잿가루지대",
        "station" : "가마솥 [6]",
        "eng_name" : "Sparkling shroomshake",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/a\/ac\/Sparkling_shroomshake.png\/revision\/latest?cb=20240423132441"
    },
    {
        "id" : 57,
        "name" : "Marinated greens",
        "type" : "Blue",
        "health" : 32,
        "stamina" : 16,
        "eitr" : 95,
        "duration" : 30,
        "healing" : 4,
        "weight" : 10,
        "stack_size" : 10,
        "biome" : "잿가루지대",
        "station" : "가마솥 [6]",
        "eng_name" : "Marinated greens",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/4\/4d\/Marinated_greens.png\/revision\/latest?cb=20240423124019"
    },
    {
        "id" : 58,
        "name" : "Ashlands gourmet bowl",
        "type" : "White",
        "health" : 75,
        "stamina" : 75,
        "eitr" : 38,
        "duration" : 50,
        "healing" : 6,
        "weight" : 100,
        "stack_size" : 5,
        "biome" : "잿가루지대",
        "station" : "Food preparation table",
        "eng_name" : "Ashlands gourmet bowl",
        "img" : "https:\/\/static.wikia.nocookie.net\/valheim\/images\/2\/28\/Ashlands_gourmet_bowl.png\/revision\/latest?cb=20241019134340"
    }
]